# @package _global_
env_type: hopper
env_name: hopper-bullet-medium-v0

# resuling optimal parameters from 20 hyper parameter optimization run (best sweep 25)
imitation: GAIL
#IL param to be optimized
imitation_epochs: 5
il_learning_rate: 0.0003
imitation_replay_size: 3
r1_reg_coeff: 1.0
# PPO param to be optimized
batch_size: 1024
ppo_epochs: 5
agent_learning_rate: 0.0003
entropy_loss_coeff: 0.01
