# @package _global_
env_type: ??
env_name: ${env_type}-expert-v2
algorithm: GAIL
replay:
  size: 3000000
pretraining:
  iterations: 100000
reinforcement:
  discount: 0.97
  target_temperature: -1.0
  polyak_factor: 0.995
imitation:
  trajectories: 10
  model:
    hidden_size: 256
    depth: 1
    input_dropout: 0.1
    dropout: 0.5
    reward_shaping: false
    subtract_log_policy: false
    reward_function: 'AIRL'
  absorbing: true
  spectral_norm: true
  learning_rate: 3.0e-05
  weight_decay: 0.0
  grad_penalty: 0.0
  entropy_bonus: 0.3
  loss_function: Mixup
  mixup_alpha: 1
  nonnegative_margin: .inf
  pos_class_prior: 0.7
  bc: false
training:
  start: 1000
