# @package _global_
env_type: ??
env_name: ${env_type}-expert-v2
algorithm: GAIL
replay:
  size: 3000000
pretraining:
  iterations: 100000
reinforcement:
  discount: 0.99
  target_temperature: -1.0
  polyak_factor: 0.99
imitation:
  trajectories: 25
  model:
    hidden_size: 512
    depth: 1
    input_dropout: 0.5
    dropout: 0.5
    reward_shaping: False
    subtract_log_policy: False
    reward_function: 'AIRL'
  absorbing: True
  spectral_norm: True
  learning_rate: 3.0e-05
  weight_decay: 0.0
  grad_penalty: 0.0
  entropy_bonus: 0.03
  loss_function: 'BCE'
  mixup_alpha: 1
  nonnegative_margin: .inf
  pos_class_prior: 0.7
  bc: False
training:
  start: 10000
