# @package _global_
env_type: walker2d
env_name: walker2d-bullet-medium-v0

imitation: GAIL
# Best IL hyperparam optimization value (reward: 579)
imitation_epochs: 5
il_learning_rate: 0.0003
imitation_replay_size: 1
r1_reg_coeff: 0.1
# PPO param to be optimized
batch_size: 1024
ppo_epochs: 20
agent_learning_rate: 0.0003
entropy_loss_coeff: 0.0
