defaults:
  - algorithm: AIRL/hopper #AIRL
  - hydra/sweeper: ax
  - hyperparam_opt: IL
seed: 0
#batch_size: 1024
evaluation:
  interval: 20000
  episodes: 30
  average_window: 5
save_trajectories: false
state_only: false
absorbing: false
#imitation_batch_size: 128
pos_class_prior: 0.5
nonnegative_margin: 0.0
render: false
# PPO constant parameters
steps: 2000000
discount: 0.99
trace_decay: 0.9
max_grad_norm: 0.5
value_loss_coeff: 0.5
ppo_clip: 0.25
hidden_size: 256
log_std_dev_init: -2


# ax sweep setting
hydra:
  run:
    dir: ./outputs/${env_type}_${imitation}/${now:%m-%d-%H-%M}
  sweep:
    dir: ./outputs/sweeper_${env_type}_${imitation}/${now:%m-%d-%H-%M}
