defaults:
  - hydra/sweeper: ax
  - algorithm: BC
  - hyperparameters:


seed: 0
steps: 100000
hidden_size: ???
discout: 0.99
trace_decay: 0.95
ppo_clip: 0.2
ppo_epochs: 4
value_loss_coeff: 0.5
entropy_loss_coeff: 0.5
learning_rate: ???
batch_size: ???
max_grad_nord: 1
evaluation_interval: 10000
evaluation_episodes: 50
save_trajectories: false
imitation: '' #heres where BC/AIRL/GAIL etc is specified. should be changed to conf file
state_only: false
absorbing: false
imitation_epochs: 5
imitation_batch_size: 128
imitation_replay_size: 4
r1_reg_coeff: 1.0
pos_class_prior: 0.5
nonnegative_margin: 0.0

# ax sweep setting
hydra:
  sweeper:
    #ax configuration. Same across all algorithms
    ax_config:
      max_trials: 20

      experiment:
        minimize: false

      early_stop:
        max_epochs_without_improvement: 5

      is_noisy: true

      params:
        hidden_size:
          type: choice
          values: [ 8, 16, 32, 64, 128 ]
        batch_size:
          type: choice
          values: [ 512, 1024, 2048 ]
        learning_rate:
          type: range
          bounds: [ 0.0001, 0.001 ]
        weight_decay:
          type: range
          bounds: [ 0.0, 0.1 ]