defaults:
  - _self_
  - algorithm: SAC/pendulum
  - hyperparam_opt: empty
  - override hydra/sweeper: basic

seed: 0
steps: 1000000
steps: 2000000
model:
  hidden_size: 256
  log_std_dev_init: -2
replay:
  size: 300000
rl:
  discount: 0.99
  learning_rate: .0001
  polyak_factor: 0.99
  max_grad_norm: 0.5
imitation:
  state_only: false
  absorbing: false
training:
  start: 10000
  batch_size: 256
evaluation:
  interval: 10000
  episodes: 30
  average_window: 5
save_trajectories: false
render: false
check_time_usage: false

# Run/sweep directories
hydra:
  run:
    dir: ./outputs/${env_type}_${algorithm}/${now:%m-%d_%H-%M-%S}
  sweep:
    dir: ./outputs/sweeper_${env_type}_${algorithm}/${now:%m-%d_%H-%M-%S}
