defaults:
  - algorithm: PPO/hopper #AIRL
  - hydra/sweeper: basic
  - hyperparam_opt: empty
seed: 0
il_learning_rate: 0.001
#batch_size: 1024
evaluation:
  interval: 20000
  episodes: 30
  average_window: 5
save_trajectories: false
state_only: false
absorbing: false
imitation_epochs: 5
imitation_batch_size: 128
imitation_replay_size: 4
r1_reg_coeff: 1.0
pos_class_prior: 0.5
nonnegative_margin: 0.0
render: false
# PPO constant parameters
steps: 2000000
discount: 0.99
trace_decay: 0.9
max_grad_norm: 0.5
value_loss_coeff: 0.5
ppo_clip: 0.25
hidden_size: 256


# ax sweep setting
hydra:
  run:
    dir: ./outputs/${env_type}_${imitation}/${now:%m-%d-%H-%M}
  sweep:
    dir: ./outputs/sweeper_${env_type}_${imitation}/${now:%m-%d-%H-%M}
