defaults:
  - environment: hopper # Check environment/hopper.yaml for PPO hyperparameters
  - hydra/sweeper: ax
  - algorithm: PPO/${defaults.0.environment} #AIRL
seed: 0
#steps: 100000
#discount: 0.99
#trace_decay: 0.95
#ppo_clip: 0.2
#ppo_epochs: 4
#value_loss_coeff: 0.5
#entropy_loss_coeff: 0.5
learning_rate: 0.001
#batch_size: 1024
evaluation_interval: 20000
evaluation_episodes: 30
save_trajectories: false
state_only: false
absorbing: false
imitation_epochs: 5
imitation_batch_size: 128
imitation_replay_size: 4
r1_reg_coeff: 1.0
pos_class_prior: 0.5
nonnegative_margin: 0.0
render: false
# PPO param from Stable baseline zoo

# ax sweep setting
hydra:
  run:
    dir: ./outputs/${env_type}_${imitation}/${now:%m-%d-%H-%M}

  sweep:
    dir: ./outputs/sweeper_${env_type}_${imitation}/${now:%m-%d-%H-%M}
    #ax configuration is moved to algorithm/<>.yaml
