defaults:
  - _self_
  - algorithm: SAC/ant
  - hyperparam_opt: empty
  - override hydra/sweeper: basic

seed: 0
steps: 1000000  # TODO: Set to 3M for seed experiments
model:
  hidden_size: 256
  activation: 'relu'
replay:
  size: 3000000
pretraining:
  iterations: 100000
  batch_size: 256
  learning_rate: 0.0001
  weight_decay: 0
reinforcement:
  discount: 0.97
  learning_rate: 0.0003
  weight_decay: 0
  polyak_factor: 0.99
  max_grad_norm: 0  # 0 to disable; only applies to RL/BC updates
imitation:
  trajectories: -1  # -1 to disable; otherwise select number of trajectories
  subsample: 20
  state_only: false
  absorbing: false
  learning_rate: 0.0003
  weight_decay: 0
training:
  start: 1000
  interval: 1
  batch_size: 256
evaluation:
  interval: 10000
  episodes: 30
  average_window: 5
save_trajectories: false
render: false
check_time_usage: false

# Run/sweep directories
hydra:
  run:
    dir: ./outputs/${env_type}_${algorithm}/${now:%m-%d_%H-%M-%S}
  sweep:
    dir: ./outputs/sweeper_${env_type}_${algorithm}/${now:%m-%d_%H-%M-%S}
