defaults:
  - _self_
  - algorithm: SAC/pendulum
  - hyperparam_opt: empty
  - override hydra/sweeper: basic

seed: 0
steps: 1000000
model:
  hidden_size: 256
  activation: 'relu'
replay:
  size: 1000000
rl:
  discount: 0.99
  learning_rate: 0.0003
  polyak_factor: 0.995
imitation:
  state_only: false
  absorbing: false
training:
  start: 10000
  interval: 100
  batch_size: 256
  max_grad_norm: 0  # 0 to disable; only applies to RL/BC updates
evaluation:
  interval: 10000
  episodes: 30
  average_window: 5
save_trajectories: false
render: false
check_time_usage: false

# Run/sweep directories
hydra:
  run:
    dir: ./outputs/${env_type}_${algorithm}/${now:%m-%d_%H-%M-%S}
  sweep:
    dir: ./outputs/sweeper_${env_type}_${algorithm}/${now:%m-%d_%H-%M-%S}
