defaults:
  - train_config  # Use default config as base
  - _self_
  - optional hyperparam_opt: ${algorithm} 
  - override hydra/sweeper: ax

hydra:
  run:
    dir: ./outputs/${algorithm}_all/${now:%m-%d_%H-%M-%S}  # Timestamp experiments up to second precision
  sweep:
    dir: ./outputs/${algorithm}_all_sweeper/${now:%m-%d_%H-%M-%S}
  sweeper:
    ax_config:
      max_trials: 30
      experiment:
        minimize: false
      early_stop:
        max_epochs_without_improvement: 5
      is_noisy: true
      params:
        training.start:
          type: choice
          values: [1000, 10000]
          value_type: int
        training.batch_size:
          type: choice
          values: [128, 256, 512, 1024]
          value_type: int
        training.learning_rate:
          type: range
          bounds: [0.00003, 0.0003]
          value_type: float
        training.weight_decay:
          type: range
          bounds: [0.0, 10.0]
          value_type: float
          log_scale: true
        reinforcement.discount:
          type: range
          bounds: [0.95, 0.99]
          value_type: float
        reinforcement.target_temperature:
          type: range
          bounds: [-1.0, -0.5]
          value_type: float
        reinforcement.polyak_factor:
          type: range
          bounds: [0.97, 0.995]
          value_type: float
