# @package _global_
env_type: hopper
env_name: hopper-bullet-medium-v0

# PPO hyperparams
steps: 2000000
batch_size: 512
discount: 0.99
trace_decay: 0.92
ppo_epochs: 20 #maybe 10 or 3 if emp study
entropy_loss_coeff: 0.0
max_grad_norm: 0.5 # related to the gradient clipping (clip_grad_norm_ )
value_loss_coeff: 0.5 #coefficient in front of value(critic) loss update
learning_rate: !!float 3e-5 # Policy learning rate
ppo_clip: 0.4 # PPO clip range
log_std_init: -2
hidden_size: 256
