# @package _global_
env_type: ant
env_name: ant-bullet-medium-v0

algorithm: DRIL
training:
  batch_size: 2048
reinforcement:
  learning_rate: 0.0003
  ppo_epochs: 5
  entropy_loss_coeff: 0.0
imitation:
  epochs: 15
  learning_rate: 0.0003
