# @package _global_
env_type: ant
env_name: ant-bullet-medium-v0

imitation: DRIL
# PPO hyperparameters
batch_size: 2048
agent_learning_rate: 0.0003
ppo_epochs: 5
entropy_loss_coeff: 0.0
# IL hyperparameters
imitation_epochs: 15
il_learning_rate: 0.0003
