# @package _global_
env_type: halfcheetah
env_name: halfcheetah-bullet-medium-v0

algorithm: DRIL
training:
  batch_size: 4096
reinforcement:
  learning_rate: 0.0003
  ppo_epochs: 5
  entropy_loss_coeff: 0.001
imitation:
  epochs: 25
  learning_rate: 0.0003
