# @package _global_
env_type: halfcheetah
env_name: halfcheetah-bullet-medium-v0

imitation: DRIL
# PPO hyperparameters
batch_size: 4096
agent_learning_rate: 0.0003
ppo_epochs: 5
entropy_loss_coeff: 0.001
# IL hyperparameters
imitation_epochs: 25
il_learning_rate: 0.0003
