# @package _global_
env_type: hopper
env_name: hopper-bullet-medium-v0

imitation: DRIL
# PPO hyperparameters
batch_size: 2048
agent_learning_rate: 0.0003
ppo_epochs: 10
entropy_loss_coeff: 0.001
# IL hyperparameters
imitation_epochs: 25
il_learning_rate: 0.00003
