# @package _global_
env_type: hopper
env_name: hopper-bullet-medium-v0

imitation: DRIL
# Resuling optimal parameters from 20 Hyper parameter optimization run (best sweep 906.7)
#IL param to be optimized
imitation_epochs: 5
il_learning_rate: !!float 3e-05 
# PPO param to be optimized
batch_size: 4096
ppo_epochs: 5
agent_learning_rate: 0.0003
entropy_loss_coeff: 0.001
