# @package _global_
env_type: ??
env_name: ${env_type}-expert-v2
algorithm: DRIL
reinforcement:
  target_temperature: -1.0
  polyak_factor: 0.995
  discount: 0.97
imitation:
  trajectories: 25
  model:
    hidden_size: 64
    depth: 2
    activation: 'relu'
    input_dropout: 0.1
    dropout: 0.75
  pretraining_iterations: 100000
  learning_rate: 0.0003
  weight_decay: 1.0
  bc: false
training:
  start: 10000
pretraining:
  iterations: 0
