# @package _global_
env_type: walker2d
env_name: walker2d-bullet-medium-v0

imitation: DRIL
# PPO hyperparameters
batch_size: 4096
agent_learning_rate: 0.0003
ppo_epochs: 10
entropy_loss_coeff: 0.001
# IL hyperparameters
imitation_epochs: 5
il_learning_rate: 0.0003
