# @package _global_
env_type: walker2d
env_name: walker2d-bullet-medium-v0

algorithm: DRIL
training:
  batch_size: 4096
reinforcement:
  learning_rate: 0.0003
  ppo_epochs: 10
  entropy_loss_coeff: 0.001
imitation:
  epochs: 5
  learning_rate: 0.0003
