# @package _global_
env_type: walker2d
env_name: walker2d-bullet-medium-v0

imitation_algorithm: DRIL
# PPO hyperparameters
training:
  batch_size: 4096
reinforcement:
  agent_learning_rate: 0.0003
  ppo_epochs: 10
  entropy_loss_coeff: 0.001
# IL hyperparameters
imitation:
  imitation_epochs: 5
  il_learning_rate: 0.0003
