# @package _global_

reinforcement:
  target_temperature: -0.5
  polyak_factor: 0.995
  discount: 0.97
imitation:
  model:
    hidden_size: 64
    depth: 1
    activation: 'relu'
    input_dropout: 0.5
    dropout: 0.1
  pretraining_iterations: 100000
  learning_rate: 3.0e-05
  weight_decay: 0.0
  bc: False
training:
  start: 1000
pretraining:
  iterations: 0
