# @package _global_

reinforcement:
  discount: 0.97
  target_temperature: -0.5
  polyak_factor: 0.99
imitation:
  model:
    hidden_size: 512
    depth: 2
    input_dropout: 0.5
    dropout: 0.5
  pretraining_iterations: 100000
  learning_rate: 0.0003
  weight_decay: 0.0
  sigma: False
  bc: False
training:
  start: 10000
