# @package _global_
env_type: ant
env_name: ant-bullet-medium-v0

# Resuling optimal parameters from 20 Hyper parameter optimization run (best sweep 615)
imitation: RED
#IL param to be optimized
imitation_epochs: 15
il_learning_rate: !!float 3e-5
# PPO param to be optimized
batch_size: 1024
ppo_epochs: 10
agent_learning_rate: !!float 3e-5
entropy_loss_coeff: 0.001
