# @package _global_
env_type: halfcheetah
env_name: halfcheetah-bullet-medium-v0

# Resuling optimal parameters from 20 Hyper parameter optimization run (best sweep -679)
imitation_algorithm: RED
#IL param to be optimized
imitation:
  imitation_epochs: 25
  il_learning_rate: !!float 3e-5
# PPO param to be optimized
training:
  batch_size: 2048
reinforcement:
  ppo_epochs: 20
  agent_learning_rate: 0.0003
  entropy_loss_coeff: 0.001
