# @package _global_
env_type: hopper
env_name: hopper-bullet-medium-v0

# Resuling optimal parameters from 20 Hyper parameter optimization run (best sweep 883)
imitation: RED
#IL param to be optimized
imitation_epochs: 25 #Benchmark
il_learning_rate: 0.0003
imitation_replay_size: 3 # Not used Benchmark
r1_reg_coeff: 0.5 # Not used
# PPO param to be optimized
batch_size: 2048 #Benchmark
ppo_epochs: 10 #Benchmark
agent_learning_rate: !!float 3e-5
entropy_loss_coeff: 0.0
