# @package _global_
env_type: ??
env_name: ${env_type}-expert-v2
algorithm: RED
reinforcement:
  discount: 0.97
  target_temperature: -0.5
  polyak_factor: 0.99
imitation:
  trajectories: 10
  model:
    hidden_size: 512
    depth: 2
    input_dropout: 0.5
    dropout: 0.5
  pretraining_iterations: 100000
  learning_rate: 0.0003
  weight_decay: 0.0
  sigma: False
  bc: false
training:
  start: 10000
