# @package _global_
env_type: walker2d
env_name: walker2d-bullet-medium-v0

# Resuling optimal parameters from 20 Hyper parameter optimization run (best sweep 761)
imitation_algorithm: RED
#IL param to be optimized
imitation:
  imitation_epochs: 25
  il_learning_rate: 0.0003
# PPO param to be optimized
training:
  batch_size: 4096
reinforcement:
  ppo_epochs: 10
  agent_learning_rate: 0.0003
  entropy_loss_coeff: 0.0
