# @package _global_
env_type: ant
env_name: ant-bullet-medium-v0

# Resuling optimal parameters from 20 Hyper parameter optimization run (best sweep 763)
imitation: GMMIL
#IL param to be optimized
self_similarity: false
# PPO param to be optimized
batch_size: 1024
ppo_epochs: 5
agent_learning_rate: !!float 3e-5
entropy_loss_coeff: 0.001
