# @package _global_
env_type: ant
env_name: ant-bullet-medium-v0

imitation: GMMIL
# PPO hyperparameters
batch_size: 1024
agent_learning_rate: 0.00003
ppo_epochs: 5
entropy_loss_coeff: 0.001
# IL hyperparameters
self_similarity: false
