# @package _global_
env_type: ant
env_name: ant-bullet-medium-v0

imitation_algorithm: GMMIL
# PPO hyperparameters
training:
  batch_size: 1024
reinforcement:
  agent_learning_rate: 0.00003
  ppo_epochs: 5
  entropy_loss_coeff: 0.001
# IL hyperparameters
imitation:
  self_similarity: false
