# @package _global_
env_type: halfcheetah
env_name: halfcheetah-bullet-medium-v0

# Resuling optimal parameters from 20 Hyper parameter optimization run (best sweep 275)
imitation: GMMIL
#IL param to be optimized
imitation_epochs: 10 # Not used
il_learning_rate: 0.0003 # Not used
imitation_replay_size: 3 # Not used
r1_reg_coeff: 0.5 # Not used
self_similarity: true
# PPO param to be optimized
batch_size: 1024
ppo_epochs: 20
agent_learning_rate: 0.0003
entropy_loss_coeff: 0.01
