# @package _global_
env_type: hopper
env_name: hopper-bullet-medium-v0

imitation: GMMIL
# PPO hyperparameters
batch_size: 2048
agent_learning_rate: 0.0003
ppo_epochs: 10
entropy_loss_coeff: 0.01
# IL hyperparameters
self_similarity: true
