# @package _global_
env_type: hopper
env_name: hopper-bullet-medium-v0

algorithm: GMMIL
training:
  batch_size: 2048
reinforcement:
  learning_rate: 0.0003
  ppo_epochs: 10
  entropy_loss_coeff: 0.01
imitation:
  self_similarity: true
