# @package _global_
env_type: hopper
env_name: hopper-bullet-medium-v0

imitation_algorithm: GMMIL
# PPO hyperparameters
training:
  batch_size: 2048
reinforcement:
  agent_learning_rate: 0.0003
  ppo_epochs: 10
  entropy_loss_coeff: 0.01
# IL hyperparameters
imitation:
  self_similarity: true
