# @package _global_
env_type: hopper
env_name: hopper-bullet-medium-v0

imitation: GMMIL
#IL param to be optimized
imitation_epochs: 10
il_learning_rate: 0.0003
imitation_replay_size: 3
r1_reg_coeff: 0.5
self_similarity: true
# PPO param to be optimized
batch_size: 512
ppo_epochs: 10
agent_learning_rate: !!float 3e-5
entropy_loss_coeff: 0.0
