# @package _global_
env_type: ant
env_name: ant-bullet-medium-v0

algorithm: AIRL
training:
  batch_size: 4096
reinforcement:
  learning_rate: 0.0003
  ppo_epochs: 20
  entropy_loss_coeff: 0.001
imitation:
  epochs: 15
  learning_rate: 0.00003
  replay_size: 3
  r1_reg_coeff: 1.0
