# @package _global_
env_type: ant
env_name: ant-bullet-medium-v0

imitation: AIRL
# PPO hyperparameters
batch_size: 4096
agent_learning_rate: 0.0003
ppo_epochs: 20
entropy_loss_coeff: 0.001
# IL hyperparameters
imitation_epochs: 15
il_learning_rate: 0.00003
imitation_replay_size: 3
r1_reg_coeff: 1.0
