# @package _global_
env_type: ant
env_name: ant-bullet-medium-v0

# Resuling optimal parameters from 20 Hyper parameter optimization run (best sweep missed)
imitation: AIRL
#IL param to be optimized
imitation_epochs: 5
il_learning_rate: 0.0003
imitation_replay_size: 1
r1_reg_coeff: 0.5
# PPO param to be optimized
batch_size: 4096
ppo_epochs: 10
agent_learning_rate: 0.0003
entropy_loss_coeff: 0.01
