# @package _global_
env_type: halfcheetah
env_name: halfcheetah-bullet-medium-v0

imitation: AIRL
# PPO hyperparameters
batch_size: 1024
agent_learning_rate: 0.0003
ppo_epochs: 20
entropy_loss_coeff: 0.001
# IL hyperparameters
imitation_epochs: 5
il_learning_rate: 0.0003
imitation_replay_size: 5
r1_reg_coeff: 0.1
