# @package _global_
env_type: halfcheetah
env_name: halfcheetah-bullet-medium-v0

algorithm: AIRL
training:
  batch_size: 1024
reinforcement:
  learning_rate: 0.0003
  ppo_epochs: 20
  entropy_loss_coeff: 0.001
imitation:
  epochs: 5
  learning_rate: 0.0003
  replay_size: 5
  r1_reg_coeff: 0.1
