# @package _global_
env_type: halfcheetah
env_name: halfcheetah-bullet-medium-v0

imitation_algorithm: AIRL
# PPO hyperparameters
training:
  batch_size: 1024
reinforcement:
  agent_learning_rate: 0.0003
  ppo_epochs: 20
  entropy_loss_coeff: 0.001
# IL hyperparameters
imitation:
  imitation_epochs: 5
  il_learning_rate: 0.0003
  imitation_replay_size: 5
  r1_reg_coeff: 0.1
