# @package _global_
env_type: hopper
env_name: hopper-bullet-medium-v0

algorithm: AIRL
training:
  batch_size: 1024
reinforcement:
  learning_rate: 0.0003
  ppo_epochs: 10
  entropy_loss_coeff: 0
imitation:
  epochs: 25
  learning_rate: 0.00003
  replay_size: 1
  r1_reg_coeff: 0.5
