# @package _global_
env_type: hopper
env_name: hopper-bullet-medium-v0

# Resuling optimal parameters from 20 Hyper parameter optimization run (best sweep missed)
imitation: AIRL
#IL param to be optimized
imitation_epochs: 5 #Benchmark
il_learning_rate: 0.0003
imitation_replay_size: 3 #Benchmark
r1_reg_coeff: 0.5
# PPO param to be optimized
batch_size: 2048 #Benchmark
ppo_epochs: 10 #Benchmark
agent_learning_rate: 0.0003
entropy_loss_coeff: 0.001
