# @package _global_
env_type: walker2d
env_name: walker2d-bullet-medium-v0

# Resuling optimal parameters from 20 Hyper parameter optimization run (best sweep 314)
imitation: AIRL
#IL param to be optimized
imitation_epochs: 15
il_learning_rate: 0.0003
imitation_replay_size: 1
r1_reg_coeff: 0.1
# PPO param to be optimized
batch_size: 1024
ppo_epochs: 10
agent_learning_rate: 0.0003
entropy_loss_coeff: 0.0
