# @package _global_
env_type: walker2d
env_name: walker2d-bullet-medium-v0

imitation: AIRL
# PPO hyperparameters
batch_size: 1024
agent_learning_rate: 0.0003
ppo_epochs: 10
entropy_loss_coeff: 0.0
# IL hyperparameters
imitation_epochs: 15
il_learning_rate: 0.0003
imitation_replay_size: 1
r1_reg_coeff: 0.1
