# @package _global_
env_type: halfcheetah
env_name: halfcheetah-bullet-medium-v0

# Resuling optimal parameters from 20 Hyper parameter optimization run (best sweep -897)
imitation: FAIRL
#IL param to be optimized
imitation_epochs: 5
il_learning_rate: !!float 3e-5
imitation_replay_size: 3
r1_reg_coeff: 0.1
# PPO param to be optimized
batch_size: 2048
ppo_epochs: 10
agent_learning_rate: !!float 3e-5
entropy_loss_coeff: 0.01
