# @package _global_
env_type: walker2d
env_name: walker2d-bullet-medium-v0

algorithm: FAIRL
training:
  batch_size: 4096
reinforcement:
  learning_rate: 0.0003
  ppo_epochs: 20
  entropy_loss_coeff: 0.01
imitation:
  epochs: 25
  learning_rate: 0.0003
  replay_size: 1
  r1_reg_coeff: 0.1
