# @package _global_
env_type: walker2d
env_name: walker2d-bullet-medium-v0

imitation: FAIRL
# PPO hyperparameters
batch_size: 4096
agent_learning_rate: 0.0003
ppo_epochs: 20
entropy_loss_coeff: 0.01
# IL hyperparameters
imitation_epochs: 25
il_learning_rate: 0.0003
imitation_replay_size: 1
r1_reg_coeff: 0.1
