# @package _global_
env_type: halfcheetah
env_name: halfcheetah-bullet-medium-v0

imitation_algorithm: BC
# PPO hyperparameters
training:
  batch_size: 1024
reinforcement:
  agent_learning_rate: 0.0003
# IL hyperparameters
imitation:
  imitation_epochs: 25
