# @package _global_
env_type: halfcheetah
env_name: halfcheetah-bullet-medium-v0

imitation: BC
# PPO hyperparameters
batch_size: 1024
agent_learning_rate: 0.0003
# IL hyperparameters
imitation_epochs: 25
