# @package _global_
env_type: halfcheetah
env_name: halfcheetah-bullet-medium-v0

# Resuling optimal parameters from 20 Hyper parameter optimization run (best sweep 652)
imitation: BC
#IL param to be optimized
imitation_epochs: 25
# PPO param to be optimized
batch_size: 1024
agent_learning_rate: 0.0003
