# @package _global_
env_type: hopper
env_name: hopper-bullet-medium-v0

# Resuling optimal parameters from 20 Hyper parameter optimization run (best sweep 1016)
imitation: BC
#IL param to be optimized
imitation_epochs: 15
# PPO param to be optimized
batch_size: 2048
agent_learning_rate:  0.0003
