# @package _global_
env_type: walker2d
env_name: walker2d-bullet-medium-v0

# Resuling optimal parameters from 20 Hyper parameter optimization run (best sweep 234)
imitation: BC
#IL param to be optimized
imitation_epochs: 5
il_learning_rate: 0.0003 # Not used
imitation_replay_size: 3 # Not used
r1_reg_coeff: 0.5 # Not used
# PPO param to be optimized
batch_size: 4096
ppo_epochs: 10 # Not used
agent_learning_rate: !!float 3e-5
entropy_loss_coeff: 0.0 # Not used
