# @package _global_
env_type: walker2d
env_name: walker2d-bullet-medium-v0

# Resuling optimal parameters from 20 Hyper parameter optimization run (best sweep 234)
imitation: BC
#IL param to be optimized
imitation_epochs: 5
# PPO param to be optimized
batch_size: 4096
agent_learning_rate: !!float 3e-5
