# @package _global_
env_type: walker2d
env_name: walker2d-bullet-medium-v0

imitation_algorithm: BC
# PPO hyperparameters
training:
  batch_size: 4096
reinforcement:
  agent_learning_rate: 0.00003
# IL hyperparameters
imitation:
  imitation_epochs: 5
