# @package _global_
env_type: halfcheetah
env_name: halfcheetah-bullet-medium-v0

algorithm: PUGAIL
training:
  batch_size: 512
reinforcement:
  learning_rate: 0.00003
  ppo_epochs: 10
  entropy_loss_coeff: 0.0
imitation:
  epochs: 10
  learning_rate: 0.0003
  replay_size: 3
  r1_reg_coeff: 0.5
  pos_class_prior: 0.5
  nonnegative_margin: 0.0
