# @package _global_
env_type: walker2d
env_name: walker2d-bullet-medium-v0

imitation_algorithm: PUGAIL
#IL param to be optimized
imitation:
  imitation_epochs: 10
  il_learning_rate: 0.0003
  imitation_replay_size: 3
  r1_reg_coeff: 0.5
# PPO param to be optimized
training:
  batch_size: 512
reinforcement:
  ppo_epochs: 10
  agent_learning_rate: !!float 3e-5
  entropy_loss_coeff: 0.0
