# @package _global_
env_type: ant
env_name: ant-bullet-medium-v0

imitation: PPO
#IL param placeholders
# PPO param to be optimized
batch_size: 2096
ppo_epochs: 20
agent_learning_rate: !!float 3e-4
entropy_loss_coeff: 0.01
