# @package _global_
env_type: ant
env_name: ant-bullet-medium-v0

imitation_algorithm: PPO
# PPO hyperparameters
training:
  batch_size: 4096
reinforcement:
  agent_learning_rate: 0.0003
  ppo_epochs: 20
  entropy_loss_coeff: 0.01
