# @package _global_
env_type: halfcheetah
env_name: halfcheetah-bullet-medium-v0

imitation: PPO
#IL param
imitation_epochs: 10
il_learning_rate: 0.0003
imitation_replay_size: 3
r1_reg_coeff: 0.5
# PPO param to be optimized
batch_size: 2048
ppo_epochs: 10
agent_learning_rate: 0.0003
entropy_loss_coeff: 0.0
