# @package _global_
env_type: halfcheetah
env_name: halfcheetah-bullet-medium-v0

imitation: PPO
# PPO param to be optimized
batch_size: 512
ppo_epoch: 10
ppo_learning_rate: !!float 3e-5
entropy_loss_coeff: 0.0
