# @package _global_
env_type: hopper
env_name: hopper-bullet-medium-v0

imitation: PPO
# PPO param to be optimized
batch_size: 512
entropy_loss_coeff: 0.0
ppo_epochs: 10
ppo_learning_rate: !!float 3e-5 # Policy learning rate
