# @package _global_
env_type: hopper
env_name: hopper-bullet-medium-v0

imitation_algorithm: PPO
# PPO hyperparameters
training:
  batch_size: 1024
reinforcement:
  agent_learning_rate: 0.0003
  ppo_epochs: 20
  entropy_loss_coeff: 0.001
