# @package _global_
env_type: pendulum
env_name: pendulum-v0

imitation: PPO
#IL param
# PPO param to be optimized
batch_size: 4096
ppo_epochs: 10
agent_learning_rate: !!float 3e-4
entropy_loss_coeff: 0.01
