# @package _global_
env_type: pendulum
env_name: pendulum-v0

imitation_algorithm: PPO
# PPO hyperparameters
training:
  batch_size: 4096
reinforcement:
  agent_learning_rate: 0.0003
  ppo_epochs: 10
  entropy_loss_coeff: 0.01
