# @package _global_
env_type: walker2d
env_name: walker2d-bullet-medium-v0

imitation: PPO
#IL param
# PPO param to be optimized
batch_size: 2048
ppo_epochs: 5
agent_learning_rate: !!float 3e-4
entropy_loss_coeff: 0.01
