# @package _global_
env_type: walker2d
env_name: walker2d-bullet-medium-v0

algorithm: PPO
training:
  batch_size: 2048
reinforcement:
  learning_rate: 0.0003
  ppo_epochs: 5
  entropy_loss_coeff: 0.01
